version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        ports:
            - "80:80"
